# SPDX-License-Identifier: GPL-2.0
#
# Makefile for rerandomizable loadable kernel module
#


test-y := test_gcc_plugin1.o test_gcc_plugin2.o
obj-$(CONFIG_SAMPLE_RERANDOMIZABLE_LKM) += test_kthread.o test.o 

obj-$(CONFIG_SAMPLE_RERANDOMIZABLE_LKM) += test_driver.o
