# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_SAMPLE_HW_BREAKPOINT) += data_breakpoint.o


# SPDX-License-Identifier: GPL-2.0
# obj-$(CONFIG_SAMPLE_HW_WATCHPOINT) += watchpoint.o trampoline.o my_data_breakpoint.o
# # obj-$(CONFIG_SAMPLE_HW_WATCHPOINT) += trampoline.o data_breakpoint.o
